### PR TITLE
Add KMS endpoint

### PR DESCRIPTION
**Pull request by YujenHsieh**
In this branch, not all functions are finished. For now, I have finished:
1. DescribeKey
2. Decrypt / Encrypt
3. EnableKey / DisableKey
4. ListAliases

For test case, I only test DescribeKey to see if something is wrong in HTTP header and also test if output can be got correctly

In file structure,
kms.go => main API callers will use to request to kms
requestStruct.go => A structure kms needs to know when request to KMS
responseStruct.go => A struct kms returns, based on which kms' API called
*_test.go => Go test

### CODE REVIEW

**Comment by alimoeeny** [comment]
Thanks @YujenHsieh 
Please run `gofmt` on `kms.go` and `responseStruct.go`
and update the pull request

**Comment by alimoeeny** [comment]
Wow, I didn't know `KMS` is already available on all regions, (except govcloud).

**Comment by YujenHsieh** [comment]
Thanks @alimoeeny 
I'm done. Could you please take a look?

**Comment by alimoeeny** [comment]
Thanks @YujenHsieh

**Pull request merged**
