### PR TITLE
Adding S3 API methods GetACL + GetCannedPolicyByAcl for getting ACL from bucket and object

### PR DESCRIPTION
**Pull request by bieli**
In some cases in https://github.com/allegro/akubra supporting tool we need two methods:

- `GetACL` from bucket and objects
- `GetCannedPolicyByAcl` based on results from `GetACL` method for checking permissions in bucket/object

It's important part to developing our next Open Source solution.
This is my proposal of solution for below functionality and new features in S3 `goamz` package.
Please comment and testing my code.

### CODE REVIEW

**Comment by alimoeeny** [comment]
@bieli thanks. Looks like there is a formatting issue. Please fix it and try this to double check.

`$ FIXIT=$(go fmt ./...); if [ -n "${FIXIT}" ]; then FIXED=$(echo $FIXIT | wc -l); echo "gofmt - ${FIXED} file(s) not formatted correctly, please run gofmt to fix them:\n ${FIXIT} " && exit 1; fi`

**Comment by alimoeeny** [comment]
Hi @bieli thanks for the update can you please sign the CLA?

**Comment by bieli** [comment]
@alimoeeny I sign th CLA and I don't know what means one not accepted check `licence/cla — Waiting for status to be reported` ? It's required to verify on your side ?

**Comment by alimoeeny** [comment]
@bieli something is wrong. I am trying to contact the gods, who have admin access to this repo (I don't) and see if I can get them to fix it or give me access to fix it.

**Comment by bieli** [comment]
@alimoeeny Any news about `licence/cla` status ?

**Comment by alimoeeny** [comment]
@bieli there is a workaround for now, sorry for the delay. Merged.

**Pull request merged**
