### PR TITLE
Fixes #351. Bug in s3.New, struct member position incorrect.

### LINKED ISSUE #351: Bug in s3.New, struct member position incorrect.
I found this when trying to use V4Signature for S3 (V4 is required in some AWS regions):
https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L98

```
// New creates a new S3.
func New(auth aws.Auth, region aws.Region) *S3 {
	return &S3{auth, region, 0, 0, 0, aws.V2Signature}
}
```

Should be:

```
// New creates a new S3.
func New(auth aws.Auth, region aws.Region) *S3 {
	return &S3{auth, region, 0, 0, aws.V2Signature, 0}
}
```

### PR DESCRIPTION
**Pull request by ziyan**

### CODE REVIEW

**Comment by ziyan** [comment]
Tagging #353

**Comment by ziyan** [comment]
Tagging to issue #351

**Comment by alimoeeny** [comment]
Thanks @ziyan

**Comment by ziyan** [comment]
@alimoeeny np :)

**Pull request merged**
