### PR TITLE
Add spot price field for LaunchConfiguration

### PR DESCRIPTION
**Pull request by gronpipmaster**

### CODE REVIEW

**Comment by alimoeeny** [comment]
Hi @gronpipmaster thanks for your contribution, would you please sign the cla ? then we can merge your commit.

**Comment by gronpipmaster** [comment]
Agreement

**Comment by gronpipmaster** [comment]
And I forgot how it's done :( Please remind me how to do this.

**Comment by alimoeeny** [comment]
mmm, good point, I guess you should see a link to https://cla-assistant.io/ but I don't see it. Maybe because I have already accepted it before. 
or maybe github is having a problem.
If you have not done this already try visiting https://cla-assistant.io/

**Comment by gronpipmaster** [comment]
I tried again, accept the rights by deleting the cookie for https://cla-assistant.io/AdRoll/goamz?pullRequest=438 and assistant show me this
scrin9
it's not affected and im see this
scrin8
I do not know what else you can do :(

**Comment by alimoeeny** [comment]
:( this looks like a github problem. 
Unfortunately I don't have access to the gods. 
Let's wait a while and see if it is solved, it must also affect other people.

**Comment by gronpipmaster** [comment]
Hi, I looked for the same problem, and found a solution https://github.com/cla-assistant/cla-assistant/issues/124

**Comment by alimoeeny** [comment]
Thanks @gronpipmaster 
Unfortunately since the ownership of the repo has changed I don't even know who has access to do this. I definitely don't. Maybe @Aaaron or @dialtone or @james-kelly can help us with this.

**Comment by alimoeeny** [comment]
Thanks @dialtone

**Pull request merged**
