### PR TITLE
Prevent double slashes in UploadSignedURL

### PR DESCRIPTION
**Pull request by hjr265**
Related to #336

### CODE REVIEW

**Comment by hjr265** [comment]
Wait a minute! I think I am losing my mind here :-o .. Give a minute and I will fix this pull request.

**Comment by alimoeeny** [comment]
@hjr265 take your time.

**Comment by hjr265** [comment]
@alimoeeny It seems the test is failing for a very weird reason.. https://travis-ci.org/AdRoll/goamz/jobs/50209129#L273

```
value *url.Error = &url.Error{Op:"Put", URL:"http://localhost:4444/bucket/name", Err:(*errors.errorString)(0xc2100a0bb0)} ("Put http://localhost:4444/bucket/name: net/http: transport closed before response was received")
```

**Comment by alimoeeny** [comment]
@hjr265  must have been a temporary CI issue, all looks good now

**Comment by hjr265** [comment]
@alimoeeny What an odd behavior from Travis.. .. All I changed was the commit message to fix the issue.. In other words, re-run the tests..

**Comment by hjr265** [comment]
@alimoeeny What an odd behavior from Travis.. .. All I changed was the commit message to fix the issue.. In other words, re-run the tests..

**Comment by alimoeeny** [comment]
In my experience it happens from time to time, CI fails with things that end up being network connectivity problem at their base. All good now.  Now that you are at it would you please also update the comment and change the `path` to `urlPath` or even better `resourcePath` or `objectPath` ?
Also there is a typo from before, "exclusing" should be "excluding" .

**Comment by alimoeeny** [comment]
I will merge now so that people who build directly off the `HEAD` won't get unexpected behavior. But will be waiting for your new PR, thanks.

**Comment by hjr265** [comment]
@alimoeeny What if we call it just "name"? Instead of urlPath, resourcePath or objectPath? To match the tone of the comment.. "path is the resource name in s3 terminalogy", but instead of that, it will now be "name is the resource name in s3 [terminology]".. .. Let me know what you think..

**Comment by alimoeeny** [comment]
@hjr265 I am all for using the AWS terminology. Go for it.

**Pull request merged**
