### PR TITLE
Added sendBatch with attributes call to sqs

### PR DESCRIPTION
**Pull request by hasSoumya**
New to Golang. Please criticize liberally :)

### CODE REVIEW

**Comment by alimoeeny** [comment]
Hi @hasSoumya one of the sqs tests fail, have a look here https://travis-ci.org/AdRoll/goamz/jobs/65975245

**Comment by hasSoumya** [comment]
Interesting. I'll take a look - I just ran it with the filter - seems I might have fat fingered my test. 
05:34:34 (master) ~/Code/Work/Go/src/github.com/AdRoll/goamz/sqs$ go test -v -cpu=4 -run=TestSendMessageBatchWithAttributes .
PASS
ok      github.com/AdRoll/goamz/sqs     0.009s

**Comment by hasSoumya** [comment]
@alimoeeny Please take at the PR at your earliest. I updated with fmt and new md5 hashes. Although, a little unsure how those values equate. I did a separate test with my own fork, things look good.

**Comment by alimoeeny** [comment]
Thank you @hasSoumya

**Pull request merged**
