### PR TITLE
ses: Support SendRawEmail operation

### PR DESCRIPTION
**Pull request by korya**
See http://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html

Note. I've omitted the `Source` ~~and `Destination`~~ (see [below](https://github.com/AdRoll/goamz/pull/411#issuecomment-159450584)) arguments for two reasons:
 - if you build the raw email message, it makes more sense to specify it during the build process and embed it in the raw message itself;
 - this puts the responsibility of verifying the sent email message solely on the user; for example, making sure that the total number of recipients is less than 50. If you use lower-level API, make sure you're doing it right.

### CODE REVIEW

**Comment by alimoeeny** [comment]
Hi @korya since you are changing the signature, let's wait a bit and see if anyone has any comments. then we'll move forward. Thanks again for the PR and thanks for fixing the tests.

**Comment by korya** [comment]
Sure, no problems.

**Comment by korya** [comment]
Update. I've played a little bit more with AWS SES, and I can see that the `Destination` argument is still required for two main reasons:
 - it is the only way to send an email message to Bcc recipients
 - it allows you to send one message per recipient as described below.

Quote from AWS documentation:
> Since most ISPs redact the email address of the recipient who submitted the
> complaint from their complaint notification, this list contains information
> about recipients who might have sent the complaint, based on the recipients
> of the original message and the ISP from which we received the complaint.
> Amazon SES performs a lookup against the original message to determine this
> recipient list.
> Because of this behavior, you can be more certain that you know which email
> address complained about your message if you limit your sending to one
> message per recipient (rather than sending one message with 30 different
> email addresses in the bcc line).

In order to send one message per recipient and still keep the original `To` and `Cc` addresses appear in the email, one can build the raw email message with these `To` and `Cc` messages and then call `SendRawEmail(rawMessage, []string{recipient})` for every recipient (i.e. every address in `To`, `Cc` and `Bcc` headers).

So my suggestion is to change the signature of `SendRawEmail` to
```go
func (s *SES) SendRawEmail(
	destinations []string,
	rawMessage []byte,
) (*SendRawEmailResponse, error) {
```

Waiting for feedback from others.

**Comment by alimoeeny** [comment]
So, @korya should we merge this as well? hopefully people have vendored their dependencies and won't be in trouble :)

**Comment by korya** [comment]
I hope so :)

The old `SendEmail()` function did not change, so there should be no compatibility issues.

The only change to API is the addition of `SendRawEmail()`. So far it fits our needs pretty well: we're being able to forward incoming emails and send out our custom emails.

So I would say yes. Let's merge! :)

**Comment by alimoeeny** [comment]
Thanks @korya

**Pull request merged**
