### PR TITLE
adding NewBoolAttributeComparison()

### PR DESCRIPTION
**Pull request by pwnsrma**

### CODE REVIEW

**Comment by alimoeeny** [comment]
Thanks @pwnsrma , is it also possible to add a test, to cover the new code? Not only to test it but also to document what values work, also what happens to null values?

**Comment by pwnsrma** [comment]
@alimoeeny, Rolling out some heavy features won't be able to add test cases now but will  do after few weeks. Please check if you can merge this without test cases.

**Comment by alimoeeny** [comment]
Thanks again @pwnsrma , OK, I can merge. Since AdRoll (who are in charge now) require you to accept the cla (see above), you need to accept it before I can merge.

**Comment by pwnsrma** [comment]
@alimoeeny Done. Thanks ..!!

**Pull request merged**
