### PR TITLE
Add AWS CA-Central-1 region

### PR DESCRIPTION
**Pull request by FrancisBou**

### CODE REVIEW

**Comment by FrancisBou** [comment]
Not sure why Travis build failed, can't seem to have any details on this, If anyone could help.

**Comment by alimoeeny** [comment]
@FrancisBou Travis is not happy because `aws/regions.go` is not formatted properly. Please make sure to run `gofmt` on it.

**Comment by alimoeeny** [comment]
@FrancisBou thanks for the PR.
Looking more into this, looks like the file `aws/regions.go` is actually properly formatted. Looks like sqs and sns are failing though don't know why

**Comment by FrancisBou** [comment]
I'm closing this pull request, I'm not able to use this library with S3 because ca-central-1 is a newer datacenter and forces you to use V4signature, wich is not currently supported for S3 in this library. 

```
2018/02/28 18:15:09 got error (status code 400)
2018/02/28 18:15:09       data:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>C948367C8001BA83</RequestId><HostId>ats7vVJkJfiDRFvCo6/TY5WANb/tC3N5jaNu3YYKzEfKObbnMVIoqyOlEurtbjjNWVai+++bgsw=</HostId></Error>
```

https://github.com/AdRoll/goamz/issues/441

**Pull request closed without merging**
