### PR TITLE
Expanded support for map type in DynamoDB

### PR DESCRIPTION
**Pull request by tgross**
For https://github.com/AdRoll/goamz/issues/308

This PR provides a UpdateExpressionUpdateAttributes method on Table that will allow us to support arbitrary UpdateExpressions to the underlying UpdateItem API endpoint.

The existing UpdateAttributes method on Table could potentially be modified to support a limited subset of UpdateExpressions, but it can't support semantics like "SET #key1.#key2=:val1" that are permitted by the DynamoDB API. Adding a new method rather than extending the existing interface will allow consuming code to avoid the complexity of writing an UpdateExpression unless it's actually needed to express operations on fields of a map (or multiple operations such as a SET and DELETE in the same call). Examples are provided in the associated test code.

Includes:
- extended dynamo Attribute struct to include Map support
- added recursive parsing of Maps in parseAttributes
- follow nested structs during output to map[string]interface{} to allow Query/Scan operations to support maps
- expanded testing of Query/Scan operations so that Map is covered

I've run the full dynamodb package's test suite via `go test -check.vv -amazon -local`

### CODE REVIEW

**Comment by alimoeeny** [comment]
Thanks @tgross , I'll be waiting for @cbroglie to comment. Please let me know when you are both happy and want to merge.  
Also thanks for adding tests .

**Comment by cbroglie** [comment]
It looks reasonable to me, but I'm really only intimately familiar with the Document/dynamizer functions.

**Comment by alimoeeny** [comment]
Thanks @cbroglie .
@tgross let's merge then and we will hopefully get more feedback and contribution from people who will use it. Thanks again.

**Comment by tgross** [comment]
I've got working code in my project using at least some of this now, so that's a good sign. Over the next week or two I'll be exercising it quite a bit, so hopefully if there are any bugs sneaking around I'll find them first.

**Pull request merged**
