### PR TITLE
Support batch operations with the Document API

### PR DESCRIPTION
**Pull request by cbroglie**
This change adds support for batch operations to the Document APIs, enabling reading/writing structs or maps in batches. Since it requires the all elements to be of the same type, batches are scoped to individual tables (like the existing Document APIs).

### CODE REVIEW

**Comment by alimoeeny** [comment]
Looking forward to your P :)

**Comment by cbroglie** [comment]
All tests are currently passing, but this isn't yet in production use. Will report back when I think it is ready to be merged.

**Comment by cbroglie** [comment]
@alimoeeny We've been using this in production for a couple weeks, I'd consider it ready to merge if you're interested.

**Comment by alimoeeny** [comment]
@cbroglie very much appreciate it.

**Pull request merged**
