### PR TITLE
s3test: Fix CommonPrefixes and NextMarker in ListObjects responses

### PR DESCRIPTION
**Pull request by abustany**

### CODE REVIEW

**Comment by abustany** [comment]
Sorry need to fix the tests for that one

**Comment by alimoeeny** [comment]
@abustany looks like 2 of the s3 test now fail, would you please have a look.

**Comment by abustany** [comment]
Test are now fixed, would you maybe have a minute to take another look at this PR? Thanks :-)

**Comment by alimoeeny** [comment]
absolutely. 
Thanks @abustany

**Pull request merged**
